apiVersion: ENC[AES256_GCM,data:dUc=,iv:Rq6kegrGwJlwDuIBdBoM2Q/1Z/O+LBbUha1gmIUmIGI=,tag:K99E+I+C2sVVmC7Q/TnO5g==,type:str]
kind: ENC[AES256_GCM,data:6dUmoi2R,iv:HQD1PXq3ibdlgurYEPJK7IyOBGfNxEaxIrGwA+FwRIM=,tag:owFwZMxwdH+eDTEaa+v1Lg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5cS7+fUuE+w=,iv:uwzzodyK4Vo3Yy+tMTOCN9jPe//LoEhd1YSx5taGoc4=,tag:UImhbm1JlC8SOj0ekotLKw==,type:str]
    namespace: ENC[AES256_GCM,data:jiuj6knkCv4nydQ=,iv:U/6YzVZLQSmUw4Vz/fCkKXov3BkNipnwkY+I8rAoUWY=,tag:wYlyp7GjFbjgV84DrxjaoQ==,type:str]
type: ENC[AES256_GCM,data:579O8ht9wY4LWWQ1erUDMCo2GPf4j5qH,iv:mkeVpO232qjBBiGri95Ew5c099OTJC0L0Y2YH6Lmvts=,tag:Lv08+wvNyJO7ARXrH7HPkw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:g6SY1lP+CQ==,iv:cUghXCP/rdhV1Cr2YZY8RmATMLIgW48tMZxFDzyCN5w=,tag:tOVjJqnHG72iu9ES7xBwHg==,type:str]
    password: ENC[AES256_GCM,data:gUBsCeikzZB8MlOwwtfQUZgQ2lq2PH37U14gXUmLdk/4t2kxpU+O5Q==,iv:69v4izSRFiPKZBTEjeYfVgH9Ap5JX9IEDxuDbAY/LaY=,tag:PWfp+3LRuYkG4qfEJD4pGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age160j4egsztq90hhv4arqke9gxpdcs72ypgxqudz2qxuvynka675tsvm5vzf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQWZCdDA4bWVtblU1bmZ4
            SmxjK0FmWXFmV0RTMFQ1cWpTSSt2cWszbGdZCnVHQzA3cUR5TDdPS09ib0JhZHpD
            RFJ4M0NsRTh1M3pNTld5RHpTM1pqOFEKLS0tIDN0amtxcU9ZanF0czVLWTNFRlFJ
            d2tiWENndUpEamJSZDNlRHRhQkdyczAKFmqnz+IIl4ytxoMVrQIlbwxGPX0+H0ND
            OYEq5zO2MUzM35RzmIiv9rBSEVM95u4Fmha2PN0hWpsLRzUS+zK41Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-22T09:10:08Z"
    mac: ENC[AES256_GCM,data:YCG4vehbpMKN6LOFeJFlCCYQwczjJT9ynSP1jZzyQawEhd3MN5poeAF13Nu4ML2+28deOdwl8MZkYKfG4YS8QjOGcvh60gmJukQBF09y6oDd3aWFG9TSQcuXgFffX0UmRGMmDrus5yZO99bCjCL1+5SznRSpDpuHsXWhU91hTbk=,iv:FifwFM25Ij1d3ee5IiNgOG4cYyrpVyJ65yc2No5hSU8=,tag:ATca4PtBVEIyEoz1x5+Low==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
