apiVersion: ENC[AES256_GCM,data:aoY=,iv:m9QbBIgs+xNps3xFfFVaNinJ3N9EOlrWEZQddjnYICY=,tag:JQ1FEB36wJjXBgJxctqhrQ==,type:str]
kind: ENC[AES256_GCM,data:ZWxvADi0,iv:teDuMQz3qrAZrIUAonhZuTpSmoIyBICC/PzZyn3ipXE=,tag:GflTz4eQAAb/TG1irF7VpQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/DHZdLssLpPvGPr4MGTy8dXECCgS1Z4kU7A=,iv:bBJym7n+POUtNGMvrBuxAelVcIjyoXjfKc9aVDFmUTc=,tag:dtpSGrRxC314dwGbwskrnQ==,type:str]
    namespace: ENC[AES256_GCM,data:iT/X4gUHnRN5/Lo=,iv:a6mbzeSE0FiLBu5sUfZfpABPCTM5EQoQoFluYKQpDk8=,tag:wDC9KjlbKkB/wyA5ZfAXgQ==,type:str]
type: ENC[AES256_GCM,data:km1LW/Vy/fmm7n5ee81S2PGF6ceP1AqYLwvperip,iv:asP2grfrOCz7nUkYSwJiPwosTzk+GOWidUI/PtQpEXY=,tag:0iB8BO9sse90NMMxGppiNw==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:L5Cad5LrWG3EIOqRu4jKq8CoIDXOJFuyZCDubyqsnonzlxFdZy2x/Mn8Jtde7v5xklAmZ86OzEmiRMwx4SGi3V8jutANN3CXz1nihrCapqbs3z2M6opX45pTEzRzpSdZs+oDjBjLmYX5upa+4rji4Ny7j6cgMfg1Z30vgFlOZ5qSA08xN6eooAn96jZtPnR3T4HiQQ==,iv:orxueGdJlEXxSxMvFuzmDUU6w84Koh2GEEuy3/gtjHk=,tag:pBpCeJIODB5qmYS24I5Wag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2u63cfmauz7gkx2gszmqtr026h29easwurp9gzt5cd9c43mxyssl2uw6f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaEE2UmF3T3RDL0dFeEdU
            UmhNUThFTHByb2cwSVg3MzNOSnY3TXVLMEFzCjNjaHc4WHREdGNtVnJmMG1VbHZx
            ODFhZ3RNK2tPZllOY1RhRVFCQVpMTzQKLS0tIE4rbEIxQ3krUkI5UTJSUk1aS2Zv
            K25aaHh6Qis3YWZRWkNLOWRUK3pmMVUKbqRaSF97frnqQ7HOIqP1fR6VkPD4NT53
            xft5iyxT6IK0C4QkFhlLHy1YO95TVqGj5jQ+31EY1jfehC5FLgYo/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-24T09:50:09Z"
    mac: ENC[AES256_GCM,data:wYqIKdUcW5ZWw5Xj4GzWMZ35cLi+oNdouzmnatzT3kxE6P3lO04tbKgfk/KewtqjZsOEat3IEiUgPHgemKlLL0vXWXjYK8uvj8LluDy/ZiIuTqXbkM7rvh91wyng4M3amFrK9rbphV2YlPeTz/8YppSMYtfU6/AQsHWJ5yOCqoA=,iv:R3cmD60rujLXj6zqPdyj350iyPCwwed+0JON/Rvvuoc=,tag:SLkwa0AZbzf9vPVByM911w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
