apiVersion: ENC[AES256_GCM,data:Ekk=,iv:+CFV2boW12yzLI6ozJZSIL3tmSf9QysaVvAOnDwN1ug=,tag:ddMmd2378V9q0by/GU9wgA==,type:str]
kind: ENC[AES256_GCM,data:fTbvoUvC,iv:wSovXSXRRbBAu+cBhI6BPWaPZMAvLLVBWPg1yqcDl0U=,tag:TWkTdDnoN9DE9PWQ0KOxAQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GRg1mXacUH8scARvsl73+Xg=,iv:zMIuYpLW0QRVdyW9oHSHAI7r8mZcy16IGw5oi03MSyk=,tag:4TA6ZbgGjO5hlbXmKC6TCQ==,type:str]
    namespace: ENC[AES256_GCM,data:aHIsgJKRAnB4G/E=,iv:1ST1TgJltq1rfG740JgHFDfvsEWx0cAvJvkinXQlmec=,tag:jjA54J+yxGzd26VRaUAPYQ==,type:str]
type: ENC[AES256_GCM,data:jcj2vrzyF2HXpjsmKs4uOQZiehQV+GUz,iv:RVumvNBYBQ6jc8KO1qayDMX7KweBbeYMPqXKhbQDJHM=,tag:umjgOm2NNU6aCklk3pDR8Q==,type:str]
stringData:
    username: ENC[AES256_GCM,data:n0AjKTFgaQ==,iv:TWFKXkv4LevBrvWNhZaskzQ/IIYc4c4vhkTdjPbNYfY=,tag:vFi6zyZU+Lzd08QLGISBIQ==,type:str]
    password: ENC[AES256_GCM,data:TMiu813ekXigdzYABLd14YzaGaeSu1yEAH/vwg==,iv:GMy2kn3sGM7tz5aqJAnblmql+dXDRx03v4CvJ7x0v34=,tag:G2B2uL1jgrAfjXGS0YpgMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2u63cfmauz7gkx2gszmqtr026h29easwurp9gzt5cd9c43mxyssl2uw6f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYm4rdW5QVHBETU9Ma3Fo
            Ti9yQ2FWaVJ4a3NOTEVNVDlFbERlSmluV0UwCng2OU9qdlFJdHY0K05BUkZROXRr
            VGdIT3ZvZWpCdzJSQmRGT0U0VU9uaWMKLS0tIEpNMlZkdHNkYXRzVWxBY0prckxw
            SXNGYmxlT0dBeVRsc05hbGFOZ25RSmsKgznnSRQ/b+B7D70iCgHXqDweQtOx1lbH
            KjbWKkbwjdi+oZYw57pwJeHaAgdttbHKNVgFYsJ5tJXkgnvwtxd86g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-24T09:50:09Z"
    mac: ENC[AES256_GCM,data:gsQ0AG7ew/dS2OssVjNDPAiIbeVMWaURoh3tiiAyqQ0/Nd3HGCbAvC+N6Hvwb6wFLTlpR9acLvRjdgdf0hF0HpgIj4FGHvUNzmvHcsUo0/WabU9x7QmPjkC8CefKrmHLn9J2qmNTNkv1VUGkfAT1IhbBFl0dZASz1GM535zU+l4=,iv:bCsLMIAkSdfvOcGmdx2Tnfv8Qso4SSgnu5906L4MUJ4=,tag:Zhld3BP460NeKnGisOpmPg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
